# Generated by Django 4.2.5 on 2023-09-09 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.CharField(max_length=30)),
                ('last_observation', models.CharField(max_length=30)),
                ('temperature', models.CharField(max_length=30)),
                ('wind', models.CharField(max_length=30)),
            ],
        ),
    ]
